[package]
name = "bench-parser"
version = "0.1.0"
edition = "2021"
publish = false

[[bench]]
name = "parser"
harness = false

[profile.release]
opt-level     = 3
lto           = "fat"
codegen-units = 1
strip         = "symbols"
debug         = false
panic         = "abort"

[dependencies]
oxc = "0.12.4"
swc_ecma_parser = "0.143.16"
swc_ecma_ast = "0.112.8"
biome_js_parser = "0.5.7"
biome_js_syntax = "0.5.7"

num_cpus = "1.16.0"
criterion  = { package = "criterion2", version = "0.7.2", default-features = false }
rayon = "1.10.0"
mimalloc = "0.1.39"

[features]
codspeed = ["criterion/codspeed"]
