[package]
name = "bench-parser"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
oxc = "0.12.2"
swc_ecma_parser = "0.143.13"
swc_ecma_ast = "0.112.7"
biome_js_parser = "0.5.7"
biome_js_syntax = "0.5.7"

num_cpus = "1.16.0"
criterion = { version = "0.5" }
rayon = "1.10.0"
mimalloc = "0.1.39"
codspeed-criterion-compat = { version = "2.4.1", default-features = false, optional = true }

[features]
codspeed = ["codspeed-criterion-compat"]

[[bench]]
name = "parser"
harness = false

[profile.release]
opt-level     = 3
lto           = "fat"
codegen-units = 1
strip         = "symbols"
debug         = false
panic         = "abort"
